"""added currency

Revision ID: 5635b6b84dc9
Revises: c4de89543dfb
Create Date: 2026-05-17 20:30:55.989182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5635b6b84dc9'
down_revision: Union[str, None] = 'c4de89543dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'currency')
    # ### end Alembic commands ###
